META-INT6/REPLANET_RestAPI_V2

build.gradle, src/main/java/metaint/replanet/rest/auth/config/RedisConfig.java, src/main/java/metaint/replanet/rest/auth/controller/MemberController.java, src/main/java/metaint/replanet/rest/auth/dto/ChangePasswordRequestDto.java, src/main/java/metaint/replanet/rest/auth/entity/Member.java, src/main/java/metaint/replanet/rest/auth/mail/controller/MailRestController.java, src/main/java/metaint/replanet/rest/auth/mail/dto/MailDto.java, src/main/java/metaint/replanet/rest/auth/mail/service/MailHandler.java, src/main/java/metaint/replanet/rest/auth/mail/service/MailService.java, src/main/java/metaint/replanet/rest/auth/service/RedisService.java, src/main/java/metaint/replanet/rest/auth/sms/controller/SmsController.java, src/main/java/metaint/replanet/rest/auth/sms/service/SmsService.java, src/main/resources/application.yml
메일 중복확인 및 메일 전송 진행중
메일 중복확인 및 메일 전송 진행중
=> [FEATURE] 회원가입 3.0.3

sql/V2script.sql, src/main/java/metaint/replanet/rest/campaign/controller/CampaignController.java, src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescription.java, src/main/java/metaint/replanet/rest/campaign/repository/ParticipationRepository.java, src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java, src/main/java/metaint/replanet/rest/reviews/controller/ReviewController.java, src/main/java/metaint/replanet/rest/reviews/dto/CampaignDTO.java, src/main/java/metaint/replanet/rest/reviews/dto/CombineReviewDTO.java, src/main/java/metaint/replanet/rest/reviews/entity/Campaign.java, src/main/java/metaint/replanet/rest/reviews/entity/Review.java, src/main/java/metaint/replanet/rest/reviews/entity/ReviewFile.java, src/main/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepository.java, src/main/java/metaint/replanet/rest/reviews/repository/ReviewMemberRepository.java, src/main/java/metaint/replanet/rest/reviews/repository/ReviewRepository.java, src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java, src/main/resources/application.yml, src/test/java/metaint/replanet/rest/campaign/controller/CampaignControllerTest.java, src/test/java/metaint/replanet/rest/campaign/service/CampaignServiceTest.java, src/test/java/metaint/replanet/rest/reviews/repository/ReviewRepositoryTest.java
바뀐 테이블 구조에 맞춰서 연관 관계 & 쿼리 전체적으로 수정
=> [FEATURE] 테이블 변경 - 사용자 추가

src/main/java/metaint/replanet/rest/chart/dto/CountAndSumByCategoryDTO.java, src/main/java/metaint/replanet/rest/chart/dto/DonationByTimeDTO.java, src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java, src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java, src/main/java/metaint/replanet/rest/chart/service/ChartService.java, src/test/java/metaint/replanet/rest/chart/repository/ChartRepositoryTest.java, src/test/java/metaint/replanet/rest/chart/repository/DonationChartRepositoryTest.java, src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
=> [Feature] 통계조회 0.2.1

sql/V2script.sql, src/main/java/metaint/replanet/rest/campaign/repository/ParticipationRepository.java, src/main/java/metaint/replanet/rest/org/controller/OrgController.java, src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java, src/main/java/metaint/replanet/rest/org/repository/OrgRepository.java, src/main/java/metaint/replanet/rest/org/service/OrgService.java, src/main/java/metaint/replanet/rest/point/controller/ExchangeController.java, src/main/resources/application.yml, src/test/java/metaint/replanet/rest/privacy/repository/privacyRepositoryService.java, src/test/java/metaint/replanet/rest/privacy/service/privacyServiceTest.java
- org 정보 수정 기능 테스트코드 작성
- 프론트에서 넘어온 데이터 받아서 업데이트 완성
- db script에 org 테이블 컬럼 추가(org 탈퇴 관련)
=> [Feature] ORG 정보 수정 0.2.1

src/main/java/metaint/replanet/rest/auth/controller/MemberController.java, src/main/java/metaint/replanet/rest/auth/exception/BadRequestException.java, src/main/java/metaint/replanet/rest/auth/sms/controller/SmsController.java, src/main/java/metaint/replanet/rest/auth/sms/service/SmsService.java
=> [FEATURE & BUGFIX] 회원가입 3.0.4

src/main/java/metaint/replanet/rest/org/controller/OrgController.java, src/main/java/metaint/replanet/rest/org/dto/OrgRequestDTO.java, src/main/java/metaint/replanet/rest/org/entity/Organization.java, src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java, src/main/java/metaint/replanet/rest/org/service/OrgService.java, src/test/java/metaint/replanet/rest/privacy/repository/privacyRepositoryService.java, src/test/java/metaint/replanet/rest/privacy/service/privacyServiceTest.java
- 기부처 리스트틀 가져갈 때 조회하는 컬럼 추가
- organization 탈퇴 신청 기능 구현
=> [Feature] ORG 정보 수정 0.2.2, 기부처 관리 0.1.1

src/main/java/metaint/replanet/rest/campaign/controller/CampaignController.java, src/main/java/metaint/replanet/rest/campaign/repository/CampaignRepository.java, src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
기부처별  진행중/종료된 캠페인 조회 서비스 추가
기부처 진행중/종료된 캠페인 2개에서 1개로 통합
=> [FEATURE] 기부처 상세페이지 조회 0.1.2

src/main/java/metaint/replanet/rest/auth/controller/MemberController.java, src/main/java/metaint/replanet/rest/auth/entity/Member.java, src/main/java/metaint/replanet/rest/auth/http/findid.http, src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java, src/main/java/metaint/replanet/rest/auth/service/MemberService.java, src/main/java/metaint/replanet/rest/auth/sms/controller/SmsController.java, src/main/resources/application.yml
id/pw 찾기 진행중
회원가입 시 문자인증 추가
phone 칼럼 unique 지정, 휴대전화 번호 중복 검사 추가
기타 정규식 보완
미사용 dependency 및 관련 설정 삭제
id/pw 찾기 진행중
=> [FEATURE & BUGFIX] 회원가입 3.1.0

src/main/java/metaint/replanet/rest/chart/dto/CountAndSumByMonthlyDTO.java, src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java, src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java, src/main/java/metaint/replanet/rest/chart/service/ChartService.java, src/test/java/metaint/replanet/rest/chart/repository/ChartRepositoryTest.java, src/test/java/metaint/replanet/rest/chart/repository/DonationChartRepositoryTest.java, src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
변경 : 조회할 통계 데이터 추가를 위해 당해 캠페인 조회 쿼리 수정
=> [Feature] 통계 조회 0.2.3

src/main/java/metaint/replanet/rest/auth/controller/MemberController.java, src/main/java/metaint/replanet/rest/auth/dto/MemberDto.java, src/main/java/metaint/replanet/rest/auth/dto/MemberPwRequestDto.java, src/main/java/metaint/replanet/rest/auth/http/findid.http, src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java, src/main/java/metaint/replanet/rest/auth/service/MemberService.java
=> [FEATURE & FIX] 회원가입 3.0.5 / CSS 수정

src/main/java/metaint/replanet/rest/reviews/dto/OrganizationDTO.java, src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
window system 텍스트 에디터 이미지 업로드 경로 fix
=> [BUGFIX] TinyMCE 텍스트 에디터 윈도우 이미지 경로 설정

src/main/java/metaint/replanet/rest/auth/config/OAuth2Config.java, src/main/java/metaint/replanet/rest/auth/controller/KakaoController.java, src/main/java/metaint/replanet/rest/auth/dto/KakaoTokenRequest.java, src/main/java/metaint/replanet/rest/auth/oauth2/PrincipalDetails.java, src/main/java/metaint/replanet/rest/auth/oauth2/PrincipalOauth2UserService.java, src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java, src/main/resources/application.yml
=> [Feature] 카카오로그인 0.1.1

src/main/java/metaint/replanet/rest/org/controller/OrgController.java, src/main/java/metaint/replanet/rest/org/repository/OrgMemberRepository.java, src/main/java/metaint/replanet/rest/org/service/OrgService.java, src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java
- ORG 정보수정 사진 변경 경로 수정(멤버코드를 경로에 추가)
- ORG 탈퇴도 모금내역 여부 따라서 처리
=> [Feature] ORG 정보 수정 0.2.5

src/main/java/metaint/replanet/rest/auth/controller/KakaoController.java, src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java
=> [Feature] 카카오 로그인 0.1.4

src/main/java/metaint/replanet/rest/bookmark/controller/BookmarkController.java, src/main/java/metaint/replanet/rest/bookmark/dto/BookmarkRegistDTO.java, src/main/java/metaint/replanet/rest/bookmark/entity/Bookmark.java, src/main/java/metaint/replanet/rest/bookmark/service/BookmarkService.java, src/main/java/metaint/replanet/rest/campaign/dto/CampaignDesOrgDTO.java, src/main/java/metaint/replanet/rest/campaign/dto/MemberDTO.java, src/test/java/metaint/replanet/rest/bookmark/service/BookmarkServiceTest.java
관심리스트 엔티티(Bookmark) 및 DTO(BookmarkDTO)
memberCode ,campaignCode int  기본자료형에서 사용자정의 자료형으로 변경
=> [FEATURE] 관심리스트 조회 수정  0.1.5

src/main/java/metaint/replanet/rest/auth/dto/MemberRequestDto.java, src/main/java/metaint/replanet/rest/auth/dto/TokenDto.java, src/main/java/metaint/replanet/rest/auth/entity/Member.java, src/main/java/metaint/replanet/rest/auth/jwt/TokenProvider.java, src/main/java/metaint/replanet/rest/auth/service/AuthService.java
=> [Feature] ORG 정보 수정 0.2.7

src/main/java/metaint/replanet/rest/org/repository/OrgRepository.java, src/main/java/metaint/replanet/rest/org/service/OrgService.java
=> [Fix] 기부처 탈퇴시 org도 함께 처리되게 로직 구현

sql/V1script.sql, sql/V2script.sql, src/main/java/metaint/replanet/rest/bookmark/entity/Bookmark.java, src/main/java/metaint/replanet/rest/bookmark/repository/BookmarkRepository.java, src/main/java/metaint/replanet/rest/bookmark/service/BookmarkService.java, src/main/java/metaint/replanet/rest/campaign/dto/CampaignDescFileDTO.java, src/main/java/metaint/replanet/rest/campaign/entity/Campaign.java, src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescFile.java, src/main/java/metaint/replanet/rest/campaign/repository/CampaignRepository.java, src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
캠페인 파일 엔티티,테이블 변경 ( fileOriginPath ) 삭제
기부처 마이페이지 진행중,종료된 모금 조회 소팅 마감임박순으로 변경
=> [BUGFIX]  캠페인 엔티티 변경 0.1.6  

src/main/java/metaint/replanet/rest/chart/repository/ChartRepository.java, src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java
변경 : 조인 테이블 null 값 발생에 따른 계산 불가 에러 해결.
=> [Fix] 통계 조회 0.2.4

src/main/java/metaint/replanet/rest/bookmark/entity/Bookmark.java, src/main/java/metaint/replanet/rest/campaign/entity/Campaign.java, src/main/java/metaint/replanet/rest/campaign/entity/CampaignDescFile.java, src/main/java/metaint/replanet/rest/campaign/entity/Organization.java, src/main/java/metaint/replanet/rest/campaign/service/CampaignService.java
=> [BUGFIX] 캠페인 엔티티, 북마크 엔티티 설정 변경 0.1.7  

src/main/java/metaint/replanet/rest/reviews/controller/ReviewController.java, src/main/java/metaint/replanet/rest/reviews/service/ReviewService.java
=> [Fix] 리뷰 등록/수정 버그 수정 중

sql/V2script.sql, src/main/java/metaint/replanet/rest/auth/controller/AuthController.java, src/main/java/metaint/replanet/rest/auth/dto/MemberRequestDto.java, src/main/java/metaint/replanet/rest/auth/dto/TokenDto.java, src/main/java/metaint/replanet/rest/auth/repository/MemberRepository.java, src/main/java/metaint/replanet/rest/auth/service/AuthService.java, src/main/java/metaint/replanet/rest/campaign/dto/MemberDTO.java, src/main/java/metaint/replanet/rest/campaign/entity/Member.java, src/main/java/metaint/replanet/rest/chart/entity/Member.java, src/main/java/metaint/replanet/rest/pay/dto/MemberDTO.java, src/main/java/metaint/replanet/rest/pay/entity/Member.java, src/main/java/metaint/replanet/rest/point/dto/MemberDTO.java, src/main/java/metaint/replanet/rest/point/entity/Member.java, src/main/java/metaint/replanet/rest/privacy/dto/MemberDTO.java, src/main/java/metaint/replanet/rest/privacy/entity/Member.java, src/main/java/metaint/replanet/rest/privacy/service/PrivacyService.java, src/main/java/metaint/replanet/rest/reviews/dto/MemberDTO.java
=> [Fix] 탈퇴회원, 탈퇴기부처회원 로그인 방지

src/main/java/metaint/replanet/rest/reviews/repository/CampaignReviewRepository.java
=> [REFACTOR] 해당 재단 리뷰 전체 조회 쿼리 수정

src/main/java/metaint/replanet/rest/auth/controller/AuthController.java
=> [Fix] Auth 디버깅용 log 추가

src/main/java/metaint/replanet/rest/chart/controller/ChartController.java, src/main/java/metaint/replanet/rest/chart/dto/DonationByTimeDTO.java, src/main/java/metaint/replanet/rest/chart/repository/DonationChartRepository.java, src/main/java/metaint/replanet/rest/chart/service/ChartService.java, src/test/java/metaint/replanet/rest/chart/service/ChartServiceTest.java
=> [Feature] 통계 조회 0.2.11
